photion/web-admin

.github/workflows/e2e.yml
package.json

Integrate Cypress with Github Actions

---

app/api/aws/AwsClient.ts
hooks/api.ts
hooks/secrets.ts
nuxt.config.js
plugins/setup.ts
tests/integration/AwsIntegration.test.ts
tests/unit/app/api/aws/AwsClient.test.ts
tests/utils/aws.ts

Store decrypted credentials in sessionStorage.

---

cypress/integration/pages/concepts/index.spec.ts
src/vue/layouts/Layout.vue
src/vue/pages/Concepts/Index.vue
src/vue/pages/Index.vue

Concepts Table UI

---

src/vue/pages/Index.vue

Click on dropzone should trigger file prompt

---

src/vue/components/pages/services/Integration.vue

Integration cards should be clickable as a whole

---

cypress/integration/pages/Index.spec.ts
cypress/integration/pages/concepts/_uuid.spec.ts
cypress/integration/pages/concepts/index.spec.ts
public/css/animations.css
public/index.html
src/main.ts
src/state/service.ts
src/vue/router.ts

Redirect the user

---

package.json
src/main.ts
src/plugins/sentry.ts
yarn.lock

Integrate Sentry 

---

yarn.lock

Integrate Sentry

---

.github/workflows/main.yml
package.json
src/plugins/sentry.ts
vue.config.js
yarn.lock

ci: build on GitHub Actions, publish on Netlify

---

.github/workflows/main.yml
cypress/integration/pages/services/aws.spec.ts
cypress/integration/pages/services/gcp.spec.ts
cypress/integration/pages/services/googleDrive.spec.ts
cypress/integration/pages/services/index.spec.ts
cypress/support/commands.js
cypress/support/index.d.ts
package.json
src/api/AbstractClient.ts
src/api/HttpClient.ts
src/api/aws/AwsClient.ts
src/models/Fragment.ts
src/state/secrets.ts
src/state/service.ts
src/vue/components/pages/services/Integration.vue
src/vue/components/pages/services/ServiceForm.vue
src/vue/pages/Services/Aws.vue
src/vue/pages/Services/Index.vue
tests/unit/app/api/aws/AwsClient.test.ts
vue.config.js
yarn.lock

test(Services): E2E tests for Pick Service workflow

---

.envrc.example.sh
README.md

Include more about the project and how to get started.
Closes #72

docs: improve README.md

---

cypress/integration/pages/Index.spec.ts
src/vue/components/ui/PhoCard.vue
src/vue/layouts/Layout.vue
src/vue/pages/Index.vue

refactor(tailwind css): update Layout and Landing page

---

cypress/integration/pages/services/aws.spec.ts
cypress/integration/pages/services/browser.spec.ts
cypress/integration/pages/services/gcp.spec.ts
cypress/integration/pages/services/googleDrive.spec.ts
cypress/integration/pages/services/index.spec.ts
cypress/support/commands.js
src/vue/components/pages/services/Integration.vue
src/vue/components/pages/services/ServiceForm.vue
src/vue/components/ui/PhoButton.vue
src/vue/components/ui/forms/PhoInputText.vue
src/vue/pages/Index.vue
src/vue/pages/Services/Aws.vue
src/vue/pages/Services/Browser.vue
src/vue/pages/Services/Gcp.vue
src/vue/pages/Services/GoogleDrive.vue
src/vue/pages/Services/Index.vue

refactor(tailwind-css): refactor Services workflow

---

src/vue/components/ui/forms/PhoInputText.vue

Just very basic styling for PhoTextField. Fixes #99

Tailwind CSS Migration: PhoTextField component

---

src/vue/components/pages/services/Integration.vue
src/vue/components/ui/PhoCard.vue
src/vue/pages/Index.vue

Some styling to Card component and clickable functionality, that is why pages/Index and services/Integration get modified, Fixes #107

Tailwind CSS Migration: PhoCard component

---

.github/workflows/main.yml

ci: speed up Netlify actions on pipeline

---

src/vue/components/pages/services/ServiceForm.vue
src/vue/components/ui/PhoButton.vue

Basic styling on button component `PhoButton`, Fixes #102

Tailwind CSS Migration: PhoButton component

---

cypress/integration/pages/concepts/_uuid.spec.ts
src/assets/scss/main.scss
src/vue/components/organisms/fragments/FragmentCard.vue
src/vue/components/pages/services/Integration.vue
src/vue/components/pages/services/ServiceForm.vue
src/vue/components/shared.ts
src/vue/components/ui/PhoButton.vue
src/vue/components/ui/PhoXCard.vue
src/vue/components/ui/forms/PhoBoolean.vue
src/vue/components/ui/forms/PhoInputText.vue
src/vue/components/ui/forms/PhoSelect.vue
src/vue/pages/Concepts/_uuid.vue
src/vue/pages/Services/Index.vue

Styling complexity should be abstracted away from component logic. We have a scss processor so it makes sense to move it there.

fix: Move styling of UI elements to main.scss

---

babel.config.js
cypress/integration/pages/concepts/_uuid.spec.ts
cypress/support/commands.js
cypress/support/index.d.ts
jest.config.js
package.json
src/main.ts
src/plugins/font-awesome.ts
src/utils.ts
src/vue/components/ui/forms/PhoSelect.vue
src/vue/components/ui/forms/PhoSelectOption.vue
tests/setup.ts
tests/unit/utils.test.ts
tests/unit/vue/components/ui/forms/PhoSelect.test.ts
tests/unit/vue/components/ui/forms/__snapshots__/PhoSelect.test.ts.snap
yarn.lock

The standard select wasn't playing nice with the multiple flag. More over, we could not style it freely.
The new component exposes an API matching the previous PhoSelect but it extends it much more, by providing a dropdown-like select experience.
**TODO**: Handle keyboard inputs (so that users can navigate the PhoSelect via the keyboard).
Closes #100

feat: Created custom PhoSelect component

---

src/vue/components/ui/forms/FontAwesomeIcon.vue
src/vue/components/ui/forms/PhoSelect.vue
src/vue/components/ui/forms/PhoSelectOption.vue
tests/unit/vue/components/ui/forms/__snapshots__/PhoSelect.test.ts.snap
yarn.lock

Reference #152
See FortAwesome/vue-fontawesome#258

fix: Implement temporary FontAwesomeIcon component.

---

src/assets/scss/main.scss

bug: Disabled button has cursor `pointer `

---

cypress/integration/pages/concepts/_uuid.spec.ts
src/vue/pages/Concepts/_uuid.vue

fix: Reroute to concepts page after concept uuid is deleted

---

cypress/integration/pages/concepts/_uuid.spec.ts
src/vue/components/ui/forms/PhoTextField.vue
src/vue/pages/Concepts/_uuid.vue
tests/unit/vue/components/ui/forms/PhoTextField.test.ts
tests/unit/vue/components/ui/forms/__snapshots__/PhoTextField.test.ts.snap

bug: Concept page date field has no validation

---

src/vue/components/ui/PhoTooltip.vue
tests/unit/vue/components/ui/PhoTooltip.test.ts
tests/unit/vue/components/ui/__snapshots__/PhoTooltip.test.ts.snap

Positioning logic and using the delays in props

Tooltip implementation

---

package.json
yarn.lock

fix: upgrade `ts jest` to match `jest` v(26)

---

public/index.html

fix: Disable zoom via viewport

---

docs/qa/test-cases/services/README.md
docs/qa/test-cases/services/aws/README.md

Create /services test plan

---

src/assets/scss/layout/_layout.scss
src/assets/scss/main.scss
src/vue/layouts/Layout.vue

added padding bottom in layout (so that it can be applied to all pages). Assigned a new class to <main> element. Made a new file _layout.scss, so that the layout styling can be written there.
Please review and let me know if you want any change.

add padding bottom on pages

---

cypress/integration/pages/concepts/_uuid.spec.ts
cypress/integration/pages/services/googleDrive.spec.ts
src/vue/components/organisms/fragments/FragmentCard.vue
src/vue/pages/Concepts/_uuid.vue

When uploading new fragments to the concept page there is no way of deleting them.
Closes #204

fix: allow removing fragments before upload

---

cypress/integration/pages/Index.spec.ts
cypress/support/commands.js
src/state/secrets.ts
src/state/service.ts
src/vue/layouts/Layout.vue

It will show just below "Photion"
Closes #232

fix: current service name should be displayed

---

src/assets/scss/components/_pho_card.scss
src/assets/scss/main.scss
src/vue/components/ui/PhoXCard.vue

I have completed required changes, please review and let me know

fix the size of service thumbnail on breakpoint: sm
